#run this commands to verify kubectl get rc
#kubectl get pods -l env=demo

apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replicationcontroller
  labels:
    env: demo
spec:
  template:
    metadata:
      labels:
        env: demo
      name: nginx-pod
    spec:
      containers:
        - image: nginx
          name: nginx
  replicas: 3