apiVersion: v1
kind: replicationController
metadata:
  name: nginx-replicationController
  labels:
    env: demo
spec:
  template:
    metadata:
      labels:
        eve: demo
      name: nginx-pod
    spec:
      containers:
        - image: nginx
          name: nginx
  replicas: 3